sudo: required
services:
  - docker

before_install:
  - docker build -t derunderyerm/multi-container-app -f ./client/Dockerfile.dev ./client

script:
  - docker run derunderyerm/multi-container-app npm test -- --coverage

after_success:
  - docker build -t derunderyerm/multi-container-app-client ./client
  - docker build -t derunderyerm/multi-container-app-server ./server
  - docker build -t derunderyerm/multi-container-app-nginx ./nginx
  - docker build -t derunderyerm/multi-container-app-worker ./worker
  # LOG in to docker cli:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push derunderyerm/multi-container-app-client 
  - docker push derunderyerm/multi-container-app-server 
  - docker push derunderyerm/multi-container-app-nginx 
  - docker push derunderyerm/multi-container-app-worker 