sudo: required
services:
  - docker

before_install:
  - docker build -t derunderyerm/multi-container-app -f ./client/Dockerfile.dev ./client

script:
  - docker run derunderyerm/multi-container-app npm test -- --coverage

after_success:
  - docker build -t derunderyerm/multi-container-app-client ./client
  - docker build -t derunderyerm/multi-container-app-server ./server
  - docker build -t derunderyerm/multi-container-app-nginx ./nginx
  - docker build -t derunderyerm/multi-container-app-worker ./worker